# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - backendtestdocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://backendtestdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ed3d1eff75784fa0bc99cb9f28f4bcc1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e71aa75593dc4a8cbfb33e87cfa368c6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: backendtestdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed3d1eff75784fa0bc99cb9f28f4bcc1 }}/backendtestdocker:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backendtestdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0e8828774f9146d0a4439b2946015b94 }}
        images: 'backendtestdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ed3d1eff75784fa0bc99cb9f28f4bcc1 }}/backendtestdocker:${{ github.sha }}'